[OpenCL]
platform_id = 0
device_id = 0
use_gpu = true
profile = true

[Hough_transform]
image =  "data/245.jpg"
min_radius = 80
max_radius = 1200
radius_threshold = 8
radius_step = 1
visualize_process = 0
hough_space_threshold = 0.98
canny_threshold1 = 8
canny_threshold2 = 80
