[OpenCL]
platform_id = 0
device_id = 0
use_gpu = true

[Image]
image =  "data/245.jpg"
resize_ratio = 0.1 # in range 0-1

[Image.Gaussian]
blur_size = 5
sigma = 1.4

[Image.Canny]
threshold1 = 8
threshold2 = 80


[Hough_transform]
min_radius = 80
max_radius = 1200
radius_threshold = 7
radius_step = 1
angle_step = 2
visualize_process = 1
hough_space_threshold = 0.92
