[OpenCL]
platform_id = 0
device_id = 0
use_gpu = true

[Hough_transform]
image =  "data/dendro.jpg"
min_radius = 1200
max_radius = 2500
radius_threshold = 50
radius_step = 5
visualize_process = 0
hough_space_threshold = 0.9
canny_threshold1 = 110
canny_threshold2 = 220
