[OpenCL]
platform_id = 0
device_id = 0
use_gpu = true

[Hough_transform]
image =  "data/dendro.jpg"
min_radius = 24
max_radius = 50
radius_threshold = 2
radius_step = 1
visualize_process = 1
hough_space_threshold = 0.9
canny_threshold1 = 110
canny_threshold2 = 150